### ISSUE TITLE
pip install of this package failed 

### ISSUE THREAD

**Issue by Etienne357** [nobeam/eleganttools#14]
pip install -U git+https://github.com/nobeam/eleganttools.git
Collecting git+https://github.com/nobeam/eleganttools.git
  Cloning https://github.com/nobeam/eleganttools.git to /tmp/pip-ZJVhEM-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ZJVhEM-build/setup.py", line 6
        about: Dict[str, str] = {}
             ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ZJVhEM-build/

**Comment by felix-andreas** [comment]
Needs at least python3.6

**Comment by felix-andreas** [comment]
I specified the required version in the install script:

https://github.com/nobeam/eleganttools/blob/59b61d336df19dc64cbb5b6981656bd6496a28c3/setup.py#L21

But python <=3.5 is not even able to parse the install script and throw a more meaningful error. The problem is the variable type annotation (see [PEP 526](https://www.python.org/dev/peps/pep-0526/)) introduced in Python 3.6. Nothing I can do here.
